In [1]:
!pip install langchain faiss-cpu tiktoken requests

In [2]:
pip install langchain

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install numpy 


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install faiss-cpu

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install euriai

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
pip install -U langchain-community

                                              0.0/2.5 MB ? eta -:--:--
                                              0.0/2.5 MB 653.6 kB/s eta 0:00:04
     -                                        0.1/2.5 MB 871.5 kB/s eta 0:00:03
     ---                                      0.2/2.5 MB 1.6 MB/s eta 0:00:02
     --------                                 0.5/2.5 MB 2.8 MB/s eta 0:00:01
     ------------                             0.8/2.5 MB 3.4 MB/s eta 0:00:01
     ----------------                         1.1/2.5 MB 3.7 MB/s eta 0:00:01
     --------------------                     1.3/2.5 MB 4.1 MB/s eta 0:00:01
     ------------------------                 1.6/2.5 MB 4.3 MB/s eta 0:00:01
     ----------------------------             1.8/2.5 MB 4.5 MB/s eta 0:00:01
     --------------------------------         2.0/2.5 MB 4.5 MB/s eta 0:00:01
     ------------------------------------     2.3/2.5 MB 4.6 MB/s eta 0:00:01
     ---------------------------------------  2.5/2.5 MB 4.6 MB/s e


[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
from langchain.embeddings.base import Embeddings
from langchain.llms.base import LLM
from typing import List,Dict,Any
import requests
import numpy as np
import faiss
import os

In [7]:
import requests
import numpy as np

def generate_embeddings(text: str):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYzZiMDAxMS1iMmJmLTQ4YjUtOTc5Yy1hOGRjODI5OTk3NzkiLCJwaG9uZSI6Iis5MTc3Mzc0OTE3OTQiLCJpYXQiOjE3NDU4NDU0MTQsImV4cCI6MTc3NzM4MTQxNH0.RSdLfZ7acGKyQxRqKdd8I_ouLZim3_WtnxXExrSXQNs"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    
    return embedding

In [8]:
from euriai import EuriaiClient
def generate_response(prompt):
    client = EuriaiClient(
        api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYzZiMDAxMS1iMmJmLTQ4YjUtOTc5Yy1hOGRjODI5OTk3NzkiLCJwaG9uZSI6Iis5MTc3Mzc0OTE3OTQiLCJpYXQiOjE3NDU4NDU0MTQsImV4cCI6MTc3NzM4MTQxNH0.RSdLfZ7acGKyQxRqKdd8I_ouLZim3_WtnxXExrSXQNs",
        model="gpt-4.1-nano"  # You can also try: "gemini-2.0-flash-001", "llama-4-maverick", etc.
    )

    response = client.generate_completion(
        prompt=prompt,
        temperature=0,
        max_tokens=300
    )

    print(response)
    return response['choices'][0]['message']["content"]

In [14]:
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

# with open("prateekinfo.txt","r") as file:
#     text = file.read()

document = TextLoader("prateekinfo.txt", encoding="utf-8").load()
document

[Document(metadata={'source': 'prateekinfo.txt'}, page_content='I am Prateek, an enthusiastic and driven final-year undergraduate student pursuing a Bachelor of Technology in Computer Science and Engineering with a specialization in Artificial Intelligence and Machine Learning from Lovely Professional University (LPU), India. With a keen passion for leveraging AI to solve real-world problems, I have progressively built a foundation of knowledge and practical experience across machine learning, computer vision, natural language processing, and DevOps tools.\n\nThroughout my academic journey, I’ve consistently sought to bridge the gap between theoretical learning and hands-on application. I have completed several high-impact training programs and certifications, including IBM’s Machine Learning Summer Training, where I developed a strong understanding of core ML algorithms, and a “Build Your Own Chatbot” course from Cognitive Class, which helped me dive deeper into conversational AI. The

In [17]:
splitter = RecursiveCharacterTextSplitter(chunk_size=300,chunk_overlap=30)
docs = splitter.split_documents(document)

In [18]:
len(docs)

30

In [19]:
texts = [doc.page_content for doc in docs]


In [20]:
texts

['I am Prateek, an enthusiastic and driven final-year undergraduate student pursuing a Bachelor of Technology in Computer Science and Engineering with a specialization in Artificial Intelligence and Machine Learning from Lovely Professional University (LPU), India. With a keen passion for leveraging',
 'a keen passion for leveraging AI to solve real-world problems, I have progressively built a foundation of knowledge and practical experience across machine learning, computer vision, natural language processing, and DevOps tools.',
 'Throughout my academic journey, I’ve consistently sought to bridge the gap between theoretical learning and hands-on application. I have completed several high-impact training programs and certifications, including IBM’s Machine Learning Summer Training, where I developed a strong understanding of',
 'a strong understanding of core ML algorithms, and a “Build Your Own Chatbot” course from Cognitive Class, which helped me dive deeper into conversational AI. 

In [24]:
# embeddings = [generate_embeddings(i).astype('float32') for i in texts]

In [28]:

embeddings = []
valid_texts = []
for i, text in enumerate(texts[0:8]):
    clean_text = text.strip()
    if not clean_text:
        print(f"skipping empty text at index {i}")
        continue
    embedding = generate_embeddings(text)
    embeddings.append(embedding)
    valid_texts.append(text)
    print(f"Processed {i+1}/{len(texts)}: {text[:30]}....->{embedding[:-5]}")

Processed 1/30: I am Prateek, an enthusiastic ....->[ 0.00998049 -0.0267054   0.00204034 ... -0.03994672  0.04222373
  0.00492218]
Processed 2/30: a keen passion for leveraging ....->[ 0.01329329 -0.02397227  0.01497392 ... -0.03330909  0.03804752
  0.0243224 ]
Processed 3/30: Throughout my academic journey....->[-0.0444049  -0.0216799   0.04547431 ... -0.05949819  0.03645722
  0.01305169]
Processed 4/30: a strong understanding of core....->[-0.02815079 -0.01751579  0.02302507 ... -0.04723567  0.01305257
  0.01486575]
Processed 5/30: model evaluation, and chatbot ....->[-0.02075444  0.00589332  0.03760185 ... -0.01814538  0.04423593
  0.00481167]
Processed 6/30: My work extends into research ....->[-0.00957852 -0.00918793  0.05456271 ... -0.03843426 -0.0073191
  0.00028581]
Processed 7/30: and Generation”. This paper ex....->[ 3.3609260e-03  4.8244423e-05  6.4259210e-02 ... -3.6864493e-02
 -9.3127545e-03 -3.4617838e-02]
Processed 8/30: fine-tuning using both TensorF....->[ 0.02264737 -

In [30]:
embeddings

[array([ 0.00998049, -0.0267054 ,  0.00204034, ...,  0.00278748,
         0.02061687,  0.02182962], shape=(1536,)),
 array([ 0.01329329, -0.02397227,  0.01497392, ..., -0.00161498,
        -0.01341   , -0.01425031], shape=(1536,)),
 array([-0.0444049 , -0.0216799 ,  0.04547431, ...,  0.01122882,
         0.00849453, -0.00175754], shape=(1536,)),
 array([-0.02815079, -0.01751579,  0.02302507, ..., -0.00821162,
         0.01166363,  0.02357134], shape=(1536,)),
 array([-0.02075444,  0.00589332,  0.03760185, ..., -0.03290817,
         0.00628009, -0.00106198], shape=(1536,)),
 array([-0.00957852, -0.00918793,  0.05456271, ...,  0.00470513,
         0.0222337 ,  0.00167354], shape=(1536,)),
 array([ 3.3609260e-03,  4.8244423e-05,  6.4259210e-02, ...,
        -2.8143601e-02,  2.3758998e-02, -2.6500884e-02], shape=(1536,)),
 array([ 0.02264737, -0.00066548,  0.05735794, ..., -0.01863786,
         0.01314934, -0.00581205], shape=(1536,))]

In [31]:
import faiss
from langchain.vectorstores.faiss import FAISS
from langchain.docstore.document import Document

In [38]:
dimension = embeddings[0].shape[0]
faiss_index = faiss.IndexFlatL2(dimension)

faiss_index.add(np.array(embeddings).astype('float32'))

In [39]:
faiss_index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001BC5CA3FBD0> >

In [45]:
generate_response("tell me about prateek poonia")

{'id': 'chatcmpl-Bbo79DgC4I8h3NVHuHEkDyubWg6tn', 'object': 'chat.completion', 'created': 1748350475, 'model': 'gpt-4.1-nano', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': 'Prateek Poonia is an Indian politician associated with the Bharatiya Janata Party (BJP). He has been active in regional politics and has held various positions within the party. Poonia is known for his work in promoting development and engaging with local communities. Please note that specific details about his career and achievements may vary or be updated over time. For the most current and detailed information, I recommend checking recent news sources or official party profiles.'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 15, 'completion_tokens': 93, 'total_tokens': 108}}


'Prateek Poonia is an Indian politician associated with the Bharatiya Janata Party (BJP). He has been active in regional politics and has held various positions within the party. Poonia is known for his work in promoting development and engaging with local communities. Please note that specific details about his career and achievements may vary or be updated over time. For the most current and detailed information, I recommend checking recent news sources or official party profiles.'

In [46]:
from langchain.chains import RetrievalQA

In [50]:
from langchain.docstore.document import Document
document = [Document(page_content=text) for text in texts[:len(embeddings)]]
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS

faiss_index = faiss.IndexFlatL2(dimension)
vector_store = FAISS(
    embedding_function = generate_embeddings,
    index = faiss_index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)
vector_store.add_documents(document)

`embedding_function` is expected to be an Embeddings object, support for passing in a function will soon be removed.


['5aece778-eeb0-44a1-93f3-c8cbb5b44a60',
 '8289001e-8e0b-431f-bac8-3c4b28f869fc',
 '4a61f36b-d969-400e-8ab4-28bc57825503',
 '13ac444d-ca36-4cef-bca5-3501bf8caf29',
 '775b104b-7753-4361-84d1-bd94f545736f',
 '6988b6e8-1f2a-4397-bb92-e72586e2d806',
 'cdf61282-bba6-441d-b8ea-11a6d5a91115',
 '43f21baf-8310-4030-8722-1c3328e315f7']

In [52]:
vector_store.save_local("faiss_index")


In [53]:
retrievar = vector_store.as_retriever(search_kwargs={"k":2})

In [56]:
from euriai import EuriaiLangChainLLM
llm = EuriaiLangChainLLM(
    api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYzZiMDAxMS1iMmJmLTQ4YjUtOTc5Yy1hOGRjODI5OTk3NzkiLCJwaG9uZSI6Iis5MTc3Mzc0OTE3OTQiLCJpYXQiOjE3NDU4NDU0MTQsImV4cCI6MTc3NzM4MTQxNH0.RSdLfZ7acGKyQxRqKdd8I_ouLZim3_WtnxXExrSXQNs",
    model = 'gpt-4.1-nano',
    temperature=0,
    max_tokens=300
)
print(llm.invoke("Write a poem about time travel"))

Through threads of time, we weave our dreams anew,  
A voyage past the dawn, into the future’s hue.  
With ticking clock as guide, we leap through history,  
A dance with moments lost, a quest for mystery.  

Anchored in the now, yet yearning to explore,  
To witness ancient skies and futures yet in store.  
Seconds become oceans, minutes turn to years,  
A tapestry of time, woven with hopes and fears.  

From bygone days of kings to stars yet to ignite,  
We chase the fleeting shadow of the endless night.  
In every tick and tock, a story lies untold,  
A journey through eternity, both daring and bold.  

So, let us trust the call of time’s mysterious rhyme,  
And venture where no foot has dared to climb—  
For in the realm of seconds and forever’s span,  
We find the soul’s adventure—time’s eternal plan.


In [58]:
rag_chain=RetrievalQA.from_chain_type(
    llm=llm,
    retriever =retrievar)

In [59]:
rag_chain("Who is prateek")

C:\Users\prate\AppData\Local\Temp\ipykernel_23536\1720794466.py:1: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  rag_chain("Who is prateek")


{'query': 'Who is prateek',
 'result': 'Prateek is a final-year undergraduate student pursuing a Bachelor of Technology in Computer Science and Engineering with a specialization in Artificial Intelligence and Machine Learning from Lovely Professional University in India. He is passionate about leveraging AI to solve real-world problems and has experience in areas such as machine learning, computer vision, natural language processing, and DevOps tools.'}

In [60]:
rag_chain("which university is prateek studying")

{'query': 'which university is prateek studying',
 'result': 'Prateek is studying at Lovely Professional University (LPU), India.'}